version: '3'
services:
  master:
    image: redis:latest
    container_name: redis_master  #master节点
    volumes:
      - ./redis/master/config/redis.conf:/etc/redis/redis.conf
      - ./redis/master/data:/data
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"  #这句话就是要加载这个路径下的配置
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - "6379:6379"
    networks:
      rsshub_net:
        ipv4_address: 172.19.0.2

  slave1:
    image: redis:latest
    container_name: redis_slave_1   #slave1节点
    volumes:
      - ./redis/slave1/config/redis.conf:/etc/redis/redis.conf
      - ./redis/slave1/data:/data
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - "6380:6379"
    networks:
      rsshub_net:
        ipv4_address: 172.19.0.3


  slave2:
    image: redis:latest
    container_name: redis_slave_2   #slave2节点
    volumes:
      - ./redis/slave2/config/redis.conf:/etc/redis/redis.conf
      - ./redis/slave2/data:/data
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - "6381:6379"
    networks:
      rsshub_net:
        ipv4_address: 172.19.0.4

  sentinel1:
    image: redis:latest
    container_name: redis_sentinel_1
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel/sentinel1/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf"
    depends_on:
      - master
    networks:
      rsshub_net:
        ipv4_address: 172.19.0.5

  sentinel2:
    image: redis:latest
    container_name: redis_sentinel_2
    ports:
      - "26380:26379"
    volumes:
      - ./redis-sentinel/sentinel2/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf"
    depends_on:
      - master
    networks:
      rsshub_net:
        ipv4_address: 172.19.0.6

  sentinel3:
    image: redis:latest
    container_name: redis_sentinel_3
    ports:
      - "26381:26379"
    volumes:
      - ./redis-sentinel/sentinel3/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: /bin/bash -c "redis-sentinel /usr/local/etc/redis/sentinel.conf"
    depends_on:
      - master
    networks:
      rsshub_net:
        ipv4_address: 172.19.0.7
networks:
  rsshub_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16